"""P1: create channels and raw_messages tables

Revision ID: 1d86a0024d90
Revises: 
Create Date: 2026-07-01 13:30:39.135366
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1d86a0024d90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rule_profile', sa.String(length=50), nullable=True),
    sa.Column('special_parser', sa.String(length=50), nullable=True),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_tg_id'), 'channels', ['tg_id'], unique=True)
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_media_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingest_status', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('dedup_status', sa.String(length=20), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('rule_version', sa.String(length=20), nullable=True),
    sa.Column('parse_attempts', sa.Integer(), nullable=False),
    sa.Column('last_parse_error', sa.Text(), nullable=True),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'tg_message_id', name='uq_rawmsg_channel_tgmsg')
    )
    op.create_index(op.f('ix_raw_messages_channel_id'), 'raw_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_raw_messages_content_hash'), 'raw_messages', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_messages_content_hash'), table_name='raw_messages')
    op.drop_index(op.f('ix_raw_messages_channel_id'), table_name='raw_messages')
    op.drop_table('raw_messages')
    op.drop_index(op.f('ix_channels_tg_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
